config/routes.rb
Rails.application.routes.draw do
  mount Payola::Engine => '/payola', as: :payola
  get "charge/:id" => 'charges#show', as: :charge
  post "charges" => 'charges#create', as: :charges
  post "cart" => "charges#cart", as: :cart

  root 'albums#index'

  get 'albums/new', as: :new_album
  get "/albums/tag/:tag_name" => "albums#tagged", as: :album_tag
  post '/albums' => 'albums#create', as: :albums
  post 'vote' => 'albums#vote', as: :vote
  devise_for :users

  get 'users/:id' => 'users#show', as: :user

  resources :relationships

end

app/models/album.rb
class Album < ActiveRecord::Base
  acts_as_taggable
  include PgSearch
  pg_search_scope :search,
                  against: [:name, :description],
                  using: {
                    tsearch: {dictionary: "english"}
                  }

  validates :name, :photo, presence: true

  mount_uploader :photo, PhotoUploader
  belongs_to :user
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  def amount
    amount_in_cents / 100.0
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/some_model.rb
class SomeModel < ActiveRecord::Base
  include Payola::Sellable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :albums
  has_many :relationships
  has_many :friends, through: :relationships, class_name: "User"
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    # @activities = PublicActivity::Activity.order("created_at desc")
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # include PublicActivity::Model
  # tracked
  before_action :authenticate_user!, only: [:vote, :new, :create]

  before_action do

    @tags = ActsAsTaggableOn::Tag.most_used

  end

  def index

    @albums = Album.all.order("likes DESC")

    @albums = @albums.search(params[:search]) if params[:search].present?

  end

  def tagged

    @albums = Album.tagged_with(params[:tag_name])

    render :index

  end

  def new

    @album = current_user.albums.new

  end

  def create
    @album = Album.all
    @album = Album.new(params_album)

    if @album.save

      redirect_to root_path

    else

      render :new

    end

  end

  def vote

    @album = Album.find(params[:id])

    @album.likes += 1

    @album.save

    redirect_to root_path

  end

  def public
    @album = Album.all
  end



  def private
  end

  def params_album

    params.require(:album).permit(:name, :photo, :post, :user_id, :tag_list, :likes)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def cart
    # add item to cart
    album = Album.find params[:album_id]

    number_already_in_cart = session[:cart][album.id.to_s].to_i
    session[:cart][album.id.to_s] = number_already_in_cart + 1
  end

  def show
    @charge = Charge.find_by stripe_charge_id: params[:id]
    redirect_to root_path, notice: "Sucessfully Subcribed"
  end

  def create
    stripe_token = params[:stripeToken]
    email = params[:stripeEmail]


    # create a stripe charge
    Stripe.api_key = ENV["STRIPE_SECRET_KEY"]
    @charge = Stripe::Charge.create(:amount => 1000,
                          :currency => "usd",
                          :card => stripe_token, # obtained with Stripe.js
                          :description => "Charge for #{email}")

    our_charge = Charge.create amount_in_cents: 1000,
                  email: email,
                  description: "Charge for #{email}",
                  stripe_charge_id: @charge.id

    # show a receipt

    redirect_to charge_path(id: @charge.id)

  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def show

    @relationship = Relationship.find(params[:id])

  end

  def create

    @relationship = Relationship.new(user_id: current_user.id, friend_id: params[:friend_id])

    @relationship.save

    redirect_to user_path (@relationship.friend_id), notice: "Successfully Follow"

  end

  def destroy

    @relationship = Relationship.where(:user_id => params[:user_id], :friend_id => params[:friend_id]).first

    @relationship.delete

    redirect_to root_path, notice: "Successfully Unfollow"

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))
    if @user.save
      sign_in @user
    end

  end

  def show

    @user = User.find(params[:id])

    @albums = Album.where(user_id: @user.id)

  end


end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/activities/index.html.erb
<!-- <h1>Feed's</h1>
<% @activities.each do |activity|
  <%= activity.inspect %>
<% end %> -->
<%= render 'payola/transactions/checkout',
      sellable: SomeModel.first %>

app/views/albums/_albums.html.erb
<center><% @albums.each do |album| %>
<div class="thumbnail">
                <!-- Button trigger modal -->
                  <%= link_to "#", data: {toggle: "modal", target: "#photo-modal#{album.id}"} do %>
                    <%= image_tag album.photo.url(:large) %>
                  <%end%>
                <!-- Modal -->
                    <div class="modal fade" id="photo-modal<%=album.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="myModalLabel"><%= album.name %></h4>
                          </div>
                          <div class="modal-body">
                              <%= image_tag album.photo.url(:large) %>
                              <hr>
                            <p><%= album.post %></p>
                            <%= link_to "Like", vote_path(id: album.id), method: :post, class: "btn btn-primary" %>
                            <div class="likeable">
                              <p>Like: <%= album.likes %></p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
 <%= link_to user_path(id: album.user_id) do%>
   <div class="btn btn-default" >
     <%= album.user.email%>
   </div>
 <%end%>

   <h3> <%= highlight(album.name, params[:search]) %></h3>
   <p><%= highlight(album.description, params[:search]) %></p>
</div>
<% end %>
</center>

app/views/albums/_likeable.html.erb
<p>Like: <%= album.likes %></p>

app/views/albums/_modal.html.erb
<% @albums.each do |album| %>
    <div class="thumbnail">
      <%= link_to user_path(id: album.user_id) do %>
        <%= image_tag album.photo.url(:large), class: "img-responsive", "data-toggle"=>"modal", "data-targer"=>"#modal-#{album.id}" %>
      <%end%>
      <%= link_to user_path(id: album.user_id) do %>
        <%= album.user.email %>
      <%end%>
        <h3> <%= highlight(album.name, params[:search]) %></h3>
        <p><%= highlight(album.description, params[:search]) %></p>
    </div>
<% end %>

app/views/albums/_popup.html.erb
<div class="row">
  <div class="col-sm-10">

    <%= image_tag photo.photo.url, class: "img-responsive" %>

    <h1> <%= photo.name %> </h1>
      <br />
    <b>File Size:</b> <%= photo.size %>
      <hr>

  </div>
</div>

app/views/albums/index.html.erb
<body>
  <%= render partial:"albums/albums"%>
</body>

app/views/albums/new.html.erb
<container>
<br />
<br />
<div class="container cntr mrgn">
  <div class="row vertical-offset-100">
    <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Upload Photo</h3>
        </div>
        <div class="panel-body">
          <%= simple_form_for @album do |f| %>
          <form accept-charset="UTF-8" role="form">
            <fieldset>
              <div class="form-group">
                <%= f.input :name %>
              </div>
              <div class="form-group">
                <%= f.input :post %>
              </div>
              <div class="form-group">
                <%= f.input :photo %>
              </div>
              <%= f.association :user, :as => :hidden %>
              <%= f.submit class: "btn btn-lg btn-primary"%>
            </fieldset>
          </form>
        <% end %>
          <br />
        </div>
      </div>
    </div>
  </div>
</div>

app/views/albums/vote.js.erb
$("#modal-<%=@photo.id%> .modal-content").html("<%= j render partial: 'details', locals: {photo: @photo} %>");

$("#modal-<%=@photo.id%>").modal("hide");

app/views/layouts/_navbar.html.erb
<center> <a href="/"> <%= image_tag "logo-01.png", class: "logo" %> </a> </center>


  <div class="row">
    <p class="navbar-text pull-left">
    </p>

    <p class="navbar-text pull-right">
      <br />
        <% if user_signed_in? %>
        Hello,<%= current_user.email %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-danger' %>
          <% else %>
          </h3>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link',class: "btn btn-primary pull-right"  %>
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link', class: "btn btn-primary pull-right"    %>
        <%end%>
    </p>


<div class="row">
  <div class="col-xs-8">
<%= link_to "Upload", new_album_path, class: "btn btn-success" %>

    <p class="navbar-text">

      <div class="col-xs-9 srch">
        <%= form_tag root_path, method: 'get' do %>
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search" %>
        <% end %>
      </div>
    </p>

  </div>
</div>
    <br /><br /><br /><br /><br />



<!-- Disabled "Success" alert so it wouldnt show up every time you log in -->
    <% if false %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wrkout</title>
  <link href="//fonts.googleapis.com/css?family=Quicksand:300,400,700" rel="stylesheet" type="text/css">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


<%= render partial:"layouts/navbar"%>

<!-- <img src="https://d1qb2nb5cznatu.cloudfront.net/startups/i/548677-614a2927735c3a4ac9e77f45b2a54e37-medium_jpg.jpg?buster=1417719928" alt="Smiley face" height="100" width="100"> -->

<%= yield %>

</body>
</html>

app/views/relationships/show.html.erb
<!-- <p class="navbar-text pull-right">
<%= link_to "Upload", new_album_path %>
<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> -->

app/views/users/show.html.erb
<% @albums.each do |album| %>
<div class="thumbnail">
<!-- Button trigger modal -->
  <%= link_to "#", data: {toggle: "modal", target: "#photo-modal#{album.id}"} do %>
    <%= image_tag album.photo.url(:large) %>
  <%end%>
<!-- Modal -->
    <div class="modal fade" id="photo-modal<%=album.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel"><%= album.name %></h4>
          </div>
          <div class="modal-body">
              <%= image_tag album.photo.url(:large) %>
              <hr>
            <p><%= album.post %></p>
            <%= link_to "Like", vote_path(id: album.id), method: :post, class: "btn btn-primary" %>
            <div class="likeable">
              <p>Like: <%= album.likes %></p>
            </div>
          </div>
        </div>
      </div>
    </div>


<%end%>

  <div class="btn btn-default" >
    <%= @user.email%>
  </div>

<% if !current_user.nil? %>
<% if !current_user.friends.include? @user %>
  <%= button_to "Follow", relationships_path(friend_id: @user.id), class: "btn btn-danger" %><br>
<%else%>
  <%= button_to "Unfollow", relationship_path(user_id: current_user.id, friend_id: @user.id), method: :delete, class: "btn btn-danger" %>

<%= form_tag charges_path, method: :post do %>
<script
  src="https://checkout.stripe.com/checkout.js"
  class="stripe-button"
  data-key="<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>"
  data-image="<%= image_path 'wrkout.jpg' %>"
  data-name="Connect with me"
  data-description="Advice($1.00)"
  data-amount="10000">
</script>
<% end %>
<%end%>
<%end%>